image: docker:latest


variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: ${DOCKER_USERNAME}/tetrisant:${CI_COMMIT_SHORT_SHA}

stages:
  - build
  - publish

build_image:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t  ${IMAGE_NAME} .
    - echo "Docker image built successfully!"
  only:
    - main  
  artifacts:
    paths:
      - dist/Tetris.jar
  
  tags:
    - dosi

manual_publish:
  stage: publish
  script:
    - echo "Publishing the application..."
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push ${IMAGE_NAME}
  when: manual
  tags:
    - dosi


  only:
    - tags
    - main