image: docker:latest

stages:
  - build

variables:
  DOCKER_IMAGE: "tetrisant_image:latest"

build:
  stage: build
  script:
    - echo "Checking files in current directory:"
    - ls -l 
    - docker build -t $DOCKER_IMAGE . 
  only:
    - main
  tags:
      - dosi
  artifacts:
    paths:
      - dist/Tetris.jar

push:
  stage: deploy 
  script:
    - docker tag $DOCKER_IMAGE $CI_REGISTRY/tetrisant_image:${CI_COMMIT_TAG}
    - docker push $CI_REGISTRY/tetrisant_image:${CI_COMMIT_TAG}
  only:
    - /^(\d+\.\d+\.\d+)$/
  when: manual
  tags:
    - dosi