image: docker:latest

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "tetrisant_image:latest"
  DOCKERHUB_USERNAME: "mdaaouan"
  DOCKERHUB_REPOSITORY: "tetrisant" 

build:
  stage: build
  script:
    - echo "Checking files in current directory:"
    - ls -l 
    - docker build --no-cache -t $DOCKER_IMAGE .  
  only:
    - main
    - /^(\d+\.\d+\.\d+)$/
  tags:
      - dosi
  artifacts:
    paths:
      - dist/Tetris.jar

push:
  stage: deploy 
  script:
    - echo "Logging into DockerHub..."
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - echo "Tagging image with version ${CI_COMMIT_TAG}..."
    - docker tag $DOCKER_IMAGE $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:${CI_COMMIT_TAG}
    - echo "Pushing image to DockerHub..."
    - docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:${CI_COMMIT_TAG}
  only:
    - /^(\d+\.\d+\.\d+)$/
  when: manual
  tags:
    - dosi
