image: docker:latest

stages:
  - build

variables:
  DOCKER_IMAGE: "tetrisant_image:latest"

build:
  stage: build
  script:
    - echo "Checking files in current directory:"
    - ls -l 
    - docker build -t $DOCKER_IMAGE . 
  only:
    - main
  tags:
      - dosi
  artifacts:
    paths:
      - dist/Tetris.jar
